name = "LaskaCore"
uuid = "9ad29ce2-7782-4744-ab48-6ef9cc0286bb"
authors = ["Elias Sj√∂lin <elias.sjolin@gmail.com>"]
version = "0.2.6"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Aqua = "0.8"
CSV = "0"
DSP = "0"
DataFrames = "1"
Dates = "1"
Mmap = "1"
NPZ = "0"
Statistics = "1"
StatsBase = "0.34.3"
Test = "1"
Unitful = "1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua"]
